// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Persistence;

#nullable disable

namespace src.Persistence.Migrations
{
    [DbContext(typeof(SuperMercadoDbContext))]
    partial class SuperMercadoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("src.Models.Articulo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nombre");

                    b.Property<double>("Precio")
                        .HasColumnType("double")
                        .HasColumnName("Precio");

                    b.HasKey("Codigo");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("src.Models.ArticuloStock", b =>
                {
                    b.Property<int>("IdArticuloStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdArticuloStock"));

                    b.Property<int>("ArticuloCodigo")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.HasKey("IdArticuloStock");

                    b.HasIndex("ArticuloCodigo");

                    b.ToTable("ArticuloStocks");
                });

            modelBuilder.Entity("src.Models.ArticuloVenta", b =>
                {
                    b.Property<int>("IdArticuloVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdArticuloVenta"));

                    b.Property<int>("ArticuloCodigo")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int?>("VentaIdVenta")
                        .HasColumnType("int");

                    b.HasKey("IdArticuloVenta");

                    b.HasIndex("ArticuloCodigo");

                    b.HasIndex("VentaIdVenta");

                    b.ToTable("ArticuloVentas");
                });

            modelBuilder.Entity("src.Models.Caja", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Numero"));

                    b.HasKey("Numero");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("src.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<int?>("CajaNumero")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Fecha");

                    b.Property<int>("NroTicket")
                        .HasColumnType("int")
                        .HasColumnName("NroTicket");

                    b.HasKey("IdVenta");

                    b.HasIndex("CajaNumero");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("src.Models.ArticuloStock", b =>
                {
                    b.HasOne("src.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("src.Models.ArticuloVenta", b =>
                {
                    b.HasOne("src.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.Venta", null)
                        .WithMany("ListaArticuloVenta")
                        .HasForeignKey("VentaIdVenta");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("src.Models.Venta", b =>
                {
                    b.HasOne("src.Models.Caja", null)
                        .WithMany("ListaVenta")
                        .HasForeignKey("CajaNumero");
                });

            modelBuilder.Entity("src.Models.Caja", b =>
                {
                    b.Navigation("ListaVenta");
                });

            modelBuilder.Entity("src.Models.Venta", b =>
                {
                    b.Navigation("ListaArticuloVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
